### ISSUE TITLE
Behavioral Models

### ISSUE THREAD

**Issue by gliperi** [gliperi/godrive-albania#11]

**Comment by DenizDaka0** [comment]
Behavioral Model
Data-Driven Models:
![Behavioral-Model-Data-Driven drawio](https://user-images.githubusercontent.com/128381400/232239816-b6abf35a-7b96-4504-a762-970fa4f7bc51.png)

Event-Driven Models:
![Behavioral-Model-Event-Driven drawio](https://user-images.githubusercontent.com/128381400/232239840-7dfc832c-3ac8-453d-a491-26c460e7c9a0.png)
