### ISSUE TITLE
External Interface Requirements

### ISSUE THREAD

**Issue by gliperi** [gliperi/godrive-albania#3]
_Deadline: 05/04/2023 23:59_

Based on the "Software Requirements Specification" Template, write the appropriate documentation on GoDrive's interface requirements

**Comment by kluka10** [comment]
a)	User Interface

GoDrive Albania software will be equipped with attractive, clear, consistent and responsive UI.
UI requirements are briefly mentioned below:
-	Easy navigation
-	Simple interface
-	Responsive
-	Consistent UI elements
-	Feedback mechanism
-	Attractive layout
-	Strategic use of color and texture
-	Provide helpful information

b)	Hardware Interface

-	Hardware required: none
-	Nature of the data: image data, text data, number data, date

c)	Software Interface Requirements

-Connection of the software with Operating system: GoDrive Albania software is developed for android, ios, windows7, windows8, windows10

d)	Communication Interface Requirements

-	Communication standards and network server communication protocols: HTTP or HTTPS
-	Electronic forms: HTML forms to get feedback and data from the user
-	Message formatting: image based, text based, number based
-	Email
-	Communication security and encryption issues
