### ISSUE TITLE
Functional Requirements

### ISSUE THREAD

**Issue by gliperi** [gliperi/godrive-albania#4]
_Deadline: 05/04/2023 23:59_

Each group should submit application specifications; i.e. the application's functional and non-functional requirements.
Write and upload the appropriate documentation regarding the specification of the application's functional requirements.

**Comment by gliperi** [comment]
Requirement #
Description:
Rationale (purpose):
Fit Criterion (prior requirements):

**Comment by ashalja02** [comment]
# Functional Requirements (Artea)
Functional requirements are the desired operations of a program, or system as defined in software development and systems engineering. It specifies the application functionality that the developers must build into the product to enable users to accomplish their tasks.

**Log in:**
- The administrator and employees can log in with their account and password.
- After logging in, they have the right to edit, add and delete information.
- Meanwhile, for a user there are two options.
- A new user must sign up. This will require to insert name, contact number, an email address and the creation of an 8-digit password.
- While an old user can log in with the profile he opened in the application before.

**Car & Reservation:**
- The system will allow staff to register new cars.
- The system will allow staff to update information of the car in need of modification.
- The system will allow staff to display all lists of cars.
- The system will allow staff to display all available car.
- Customer will be able to search the car name and then sort them by price or year model.
- By clicking on a specific car all the details will show up such as: Name and model with picture; Registration number; Fuel consumption; Insurance details; Cost; Availability; Previous feedbacks etc.
- The system will allow the customers to cancel reservation using reservation confirmation number.
- The system will also allow the employee to view every action made by customers.

**Calculate cost:**
- The user can calculate the cost for the renting process after selecting the car.
- The cost will be calculated using input and the cost information in the system such as: Time duration(days), car brand etc.

**Collect feedback from customer:**
- The user will be provided by a new tab where he can add feedback about the car and the service provided.
- Admin can read feedback and then decide to send it to the history of customer activities.
- Then every user can see the feedbacks.
