### ISSUE TITLE
Non-functional Requirements

### ISSUE THREAD

**Issue by gliperi** [gliperi/godrive-albania#5]
_Deadline: 05/04/2023 23:59_

Each group should submit application specifications; i.e. the application's functional and non-functional requirements.
Write and upload the appropriate documentation regarding the specification of the application's non-functional requirements.

**Comment by DenizDaka0** [comment]
### Non-Functional System Requirements

1. Performance: the system should be able to handle a certain number of users and respond within a specific time frame. 
1.1 Optimizing the algorithms and data structures: We should minimize the number of operations used to perform a task by optimizing the algorithms and data structures.
1.2 Optimizing network usage: We should minimize the amount of data transmitted over the network and use low-sized data by optimizing network usage.
1.3 Improving the database performance: We should use indexes and caching techniques to speed up database queries and reduce the number of databases calls to improve the database performance.
1.4 Using optimized code: We should optimize the code by removing unnecessary code, reducing the number of function calls, and optimizing loops and conditionals to use optimized code.
2. Usability: the system should be easy to use, intuitive, and provide clear and concise feedback to the users.
2.1 User-Centered Design: We should design the application with the user in mind by identifying the user's needs and preferences and creating a design that is intuitive, user-friendly, and easy to use with a user-centered design.
2.2 Simplify Navigation: We should ensure that the navigation is simple and easy to use by providing clear and concise labels and making sure that the user can easily find what they are looking for with simplified navigation.
2.3 Reduce Cognitive Load: We should avoid unnecessary complexity and information overload by simplifying the interface and providing only the information that is necessary to reduce cognitive load.
2.4 Consistent and Clear Design: We should maintain consistency throughout the design of the application by using clear and concise language and following consistent patterns in layout, color, and typography to achieve a consistent and clear design.
3. Security: the system should have the necessary security measures in place to protect against unauthorized access, data breaches, and other security threats.
3.1 Secure Coding Practices: We should use secure coding practices, such as input validation, error handling, and proper authentication and authorization mechanisms, to prevent security vulnerabilities in the application with secure coding practices.
3.2 Strong Passwords: We should encourage users to create strong passwords and enforce password policies that require regular password changes and prohibit the use of weak passwords by promoting the use of strong passwords.
3.3 Use Encryption: We should use encryption to protect sensitive data, both in transit and at rest. This includes using secure protocols, such as HTTPS, and encryption algorithms, such as AES to use encryption.
4. Reliability: the system should be able to function as intended without crashing or producing errors.
4.1 Continuous Integration and Deployment: We should use continuous integration and deployment practices to ensure that code changes are properly tested and integrated into the application without introducing new errors or issues with continuous integration and deployment.
4.2 Load Balancing: We should use load balancing techniques to distribute the workload across multiple servers to prevent overloading and system crashes by implementing load balancing.
4.3 Backup and Recovery: We should implement a backup and recovery plan to ensure that data is not lost in case of a system failure or data corruption by implementing backup and recovery.
5. Maintainability: the system should be easy to maintain and update, with clear documentation and code structure.
5.1 Consistent Coding Practices: We should use consistent coding practices, such as naming conventions, code formatting, and commenting, to make it easier for developers to understand and modify the code by maintaining consistent coding practices.
5.2 Modular Architecture: We should use a modular architecture to break down the application into smaller, independent components that can be easily modified or replaced without affecting other parts of the application with modular architecture.
5.3 Documentation: We should provide comprehensive documentation, including user manuals, technical documentation, and code documentation, to help developers understand the application and make modifications more easily by providing documentation.
6. Scalability: the system should be able to handle increasing amounts of data or users without compromising performance.
6.1 Horizontal Scaling: We will use horizontal scaling techniques, such as load balancing and auto-scaling, to distribute the workload across multiple servers and increase the capacity of the system.
6.2 Caching: We will use caching techniques to store frequently accessed data in memory and reduce the number of requests to the database or other external systems.
6.3 Stateless Architecture: We will use a stateless architecture, where each request is independent and does not rely on previous requests, to make it easier to scale horizontally.
7. Portability: the system should be able to run on different platforms and environments.
7.1 Minimize Platform-Specific Code: We will minimize the use of platform-specific code and libraries and use cross-platform alternatives when possible.
7.2 Use Standard Protocols: We will use standard protocols, such as HTTP, SMTP, or FTP, to ensure that the application can communicate with other systems and services regardless of the platform or environment.
7.3 Test on Multiple Platforms: We will test the application on multiple platforms and environments to ensure that it works correctly and does not have any platform-specific issues.
8. Availability: the system should be available for use at all times, with minimal downtime or scheduled maintenance.
8.1 Load Balancing: We will use load balancing techniques to distribute the workload across multiple servers and prevent any single server from becoming overloaded.
8.2 Automatic Scaling: We will use automatic scaling techniques, such as auto-scaling or elastic load balancing, to automatically adjust the system capacity based on demand and prevent overload or downtime.
8.3 Proactive Maintenance: We will perform proactive maintenance, such as regular system updates and patches, to prevent potential issues and reduce the risk of failures or outages.
8.4 Data Replication: We will use data replication techniques, such as mirroring or log shipping, to ensure that data is always available and up-to-date even in case of a failure or outage.
9. Compliance: the system should comply with applicable laws, regulations, and standards.
9.1 Compliance Framework: We will implement a compliance framework, such as ISO/IEC 27001 or PCI DSS, that provides guidelines and requirements for information security and data protection.
9.2 Access Controls: We will implement access controls to ensure that only authorized users can access sensitive data or perform critical functions.
9.3 Data Protection: We will implement data protection techniques, such as encryption or data masking, to protect sensitive data and prevent unauthorized access or disclosure.
9.4 Security Testing: We will perform security testing, such as penetration testing or vulnerability scanning, to identify potential security issues or compliance gaps.
9.5 Regular Audits: We will conduct regular audits to assess the compliance of the application and identify potential issues or non-compliance areas.
10. Localization: the system should support multiple languages, currencies, and cultural conventions.
10.1 Internationalization: We will implement internationalization techniques, such as Unicode support and date/time formatting, to ensure that the application can handle different languages and regions.
10.2 User Feedback: We will solicit feedback from users in different regions and languages to identify issues and opportunities for improvement in the localization of the application.
10.3 Cultural Adaptation: We will adapt the application to different cultures and regions by considering local customs, values, and preferences.
10.4 User Testing: We will conduct user testing with representatives from different regions and languages to ensure that the application is accessible and usable for all users.
11. Data Privacy: the system should protect the privacy of sensitive user data and adhere to data protection laws.
11.1 Data Classification: We classify data based on its sensitivity level and implement appropriate controls and protections for each classification level.
11.2 Access Controls: We implement access controls to ensure that only authorized users can access sensitive data.
11.3 Data Anonymization: We anonymize data, such as by replacing identifiable information with pseudonyms, to prevent unauthorized access or disclosure.
