### ISSUE TITLE
Interaction Models

### ISSUE THREAD

**Issue by gliperi** [gliperi/godrive-albania#9]

**Comment by kluka10** [comment]
![unnamed](https://user-images.githubusercontent.com/128375166/232869626-f9612b77-e84c-4b1a-ab60-5c4381dcc78c.png)
![unnamed (1)](https://user-images.githubusercontent.com/128375166/232869652-af0ef28e-81b5-4b92-a48f-1df741adecab.png)
![unnamed (2)](https://user-images.githubusercontent.com/128375166/232869666-06eaa077-cf86-4438-95c6-629e8a8b6759.png)
![unnamed (3)](https://user-images.githubusercontent.com/128375166/232869689-c1852efa-2250-4c58-a096-1058eb77b009.png)
![unnamed (4)](https://user-images.githubusercontent.com/128375166/232869707-96d624df-b6bf-4e80-ad74-5f58ba6bf17b.png)
![unnamed (5)](https://user-images.githubusercontent.com/128375166/232869721-6dff8d06-8340-4b26-bc5c-be16504fa2b8.png)
![unnamed (6)](https://user-images.githubusercontent.com/128375166/232869734-9e4b37ed-bc96-4ac1-b41a-45f09c94de66.png)
![image (6)](https://user-images.githubusercontent.com/128375166/232869746-abe6b3e0-4ad4-4bc0-85f9-34f35c0ad58c.png)
